version: '3.8'

services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sensores
      MYSQL_USER: iotuser
      MYSQL_PASSWORD: iotpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: iotuser
      PMA_PASSWORD: iotpass

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"

  node-red:
    image: nodered/node-red
    container_name: node-red
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    depends_on:
      - mysql

  thingsboard:
    image: thingsboard/tb-postgres
    container_name: thingsboard
    restart: always
    ports:
      - "8080:8080"
      - "1883:1883"  # MQTT
    environment:
      TB_QUEUE_TYPE: in-memory
      MQTT_ENABLED: "true"

  snmp-agent:
    build: ./snmpd
    container_name: snmp-agent
    restart: always
    ports:
      - "161:161/udp"
    environment:
      SNMP_RO_COMMUNITY: "public"

volumes:
  mysql-data:
  node_red_data:
